
name: Blog Starter Template
highlighter: pygments
markdown: kramdown
disqus: # disqus-username
google_analytics_id: '' # XY-99999999-9

description: Jekyll Based Blog Starter Template with Pygments Highlighter

author:
  name: ''
  email: ''
  github: # gitHub-username
  linkedin: # profile-id
  email_md5: '' # used for gravatar sidebar user image

BASE_PATH:

rss_path: rss.xml